### ISSUE TITLE
How Can i Contact You?

### ISSUE THREAD

**Issue by free1hrdp** [M-Zubair10/CaptchaXpert#5]
Hello Zubair How can i contact you can u provide telegram or something?

**Comment by M-Zubair10** [comment]
Email: ***@***.***

Moreover I can make discord group if you guys request, I don't have
telegram etc

**Comment by free1hrdp** [comment]
Yes Making discord Server better if u can do know i want to ask you some questions

**Comment by M-Zubair10** [comment]
Check out this server
https://discord.gg/BCfVDE4sv3
